### ISSUE TITLE
latest changes with new command are not released on ansible galaxy yet

### ISSUE THREAD

**Issue by JensTimmerman** [exploide/ansible-role-dnf-automatic#3]
I was reading and using the documentation like in the readme file, however the version here in master is newer then the latest release on ansible galaxy, so the new commands documentend in the readme don't work with the role in the readme yet (Swtiching to 'https://github.com/exploide/ansible-role-dnf-automatic.git' as a src for the role does work)

**Comment by exploide** [comment]
Maybe I forgot that, not sure. I don't use the role by myself at the moment. But I'm willing to fix bugs and accept pull requests if people like it.

Just reimported the role at Galaxy. I also needed to adapt the versioning scheme to semver to please the Galaxy importer.

Please try again and feel free to report back if it still doesn't work.
